### ISSUE TITLE
Ionic 5 error :  java.lang.ClassNotFoundException: by.alon22.cordova.firebase.FirebaseVisionPlugin

### ISSUE THREAD

**Issue by osmanraifgunes** [alon22/cordova-plugin-firebase-mlvision#13]
Any help will be appreciated. I am trying to solve also. If I can find a solution will post here.

```
W/System.err: java.lang.ClassNotFoundException: by.alon22.cordova.firebase.FirebaseVisionPlugin
W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:62)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:79)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:62)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:48)
        at com.portiga.diaplugin.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:7916)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7903)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3285)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3459)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "by.alon22.cordova.firebase.FirebaseVisionPlugin" on path: DexPathList[[zip file "/data/app/com.portiga.diaplugin-ojtQzqq22D2ZUrApKAv03g==/base.apk"],nativeLibraryDirectories=[/data/app/com.portiga.diaplugin-ojtQzqq22D2ZUrApKAv03g==/lib/arm64, /data/app/com.portiga.diaplugin-ojtQzqq22D2ZUrApKAv03g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 27 more
I/System.out: Error adding plugin by.alon22.cordova.firebase.FirebaseVisionPlugin.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.portiga.diaplugin, PID: 31958
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.portiga.diaplugin/com.portiga.diaplugin.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3459)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:62)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:79)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:62)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:48)
        at com.portiga.diaplugin.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:7916)
        at android.app.Activity.performCreate(Activity.java:7903)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3285)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3459) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.app.ActivityThread.main(ActivityThread.java:7564) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
D/OOMEventManagerFK: checkEventAndDumpForJE: 0
I/Process: Sending signal. PID: 31958 SIG: 9

```

**Comment by osmanraifgunes** [comment]
Solved by moving android package to under java folder.

**Comment by nick-pereira** [comment]
Hey, @osmanraifgunes I am facing the same issue. Would be helpful if you could elaborate on the fix, Thanks

> Solved by moving android package to under java folder.

**Comment by pedrumgolriz** [comment]
Bump. Cannot figure this out.. I wish Ionic wouldn't push packages that are abandoned

**Comment by pedrumgolriz** [comment]
Ok so this is what he @osmanraifgunes meant:
<img width="765" alt="Screen Shot 2022-09-21 at 4 35 27 PM" src="https://user-images.githubusercontent.com/5402482/191605338-3e2de91b-9e63-4792-ad41-8d8cfedc7d52.png">
Move the "by" folder under java


Update:

This was starting to annoy me because anytime I updated my project I'd run into this error, Google it, and end up on this thread over and over. Fix now is to simply edit the Plugin.xml and change the source-file src to include src on lines 50,51:

```
<source-file src="src/android/FirebaseVisionPlugin.java" target-dir="src/by/alon22/cordova/firebase"/>
<source-file src="src/android/FirebaseUtils.java" target-dir="src/by/alon22/cordova/firebase"/>
```
